name: Test install-task
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Cached install (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Task
        uses: ./
      - name: Verify task
        run: |
          which task
          task --version

  test-cache-miss:
    name: Forced cache miss (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Task
        uses: ./
        with:
          use-cache: "false"
      - name: Verify task
        run: |
          which task
          task --version
